### ISSUE TITLE
<Question> What is the best way to handle automatic reconnections?

### ISSUE THREAD

**Issue by jonnysmith1981** [ohjames/rxjs-websockets#1]
In the event that the network drops and then picks back up, how do you tell the socket to automatically reconnect?

**Comment by ohjames** [comment]
The connectionStatus observable produces a count of the number of connected sockets (which will always be 0 or 1 for a `shared()` observable. Please reopen if you have further questions. Hope that helps.

**Comment by ohjames** [comment]
As for automatically reconnecting, you can use `.retry()` which is a built-in rxjs operator. I'd combine with another operator to delay each reconnection attempt.

**Comment by ohjames** [comment]
Deleted my previous comments, am too unwell at the moment to make sense :P I will paste an example in here in the next couple days, but in the meantime you can look into rxjs' `retry` operator.

**Comment by ohjames** [comment]
Here's an example from some of my own code:

```javascript
    const {messages, connectionStatus} = websocketConnect(
      `ws://${window.location.hostname}:${wsPort}/ws`,
      this.input = new QueueingSubject<any>()
    )

    this.messages = messages.share().retryWhen(errors => errors.delay(1000))
```

If you are compartmentalising your rxjs build (e.g. for angular 2) you'll need the following imports:

```javascript
import 'rxjs/add/operator/share'
import 'rxjs/add/operator/retryWhen'
import 'rxjs/add/operator/delay'
```

You could also subscribe to `connectionStatus` if you want to be notified when the socket connects and disconnects, it is of type `Observer<number>`.
