### ISSUE TITLE
7.0+ API difficult to reason about

### ISSUE THREAD

**Issue by jcairney** [ohjames/rxjs-websockets#116]
Hi James,

This is not a bug, this is just the only avenue I could find to give feedback.  Back in 2017 my team started using your angular2-websocket-service library at the point where it was still a service.  I started this week to upgrade from versions of Angular from 4 to 8, and needed to move up to using rxjs-websockets because the version of RxJS included in angular2-websocket-service was not compatible with the version of RxJS I had rolled up to in my project.  Looking at your latest readme.md, I'm barely been able to understand the new API you've implemented in version 7.0 without a lot of head scratching.  I've looked through the source code of the library and I find the internals equally difficult to reason about now, compared to what it was two years ago.  I've looked through the commits to try and understand when the changes occurred and why they were made.

Specifically the change away from taking an input observable in the connect method, in the January 7th commit - eaf8fc411f4bbb6f6ca10c57622ef10432e6117d - has a commit message to the effect of "simplify connection status handling", but I think it doesn't simplify the library as a whole.  It was easier to reason about the system when one was passing in a stream of input.  Now the input is somehow supplied through something we subscribe to the output.  I get that we are receiving a factory as output when we subscribe, but it's still convoluted in my opinion, and the naming doesn't help sort it out.  I'm sure I'll be able to figure it out.  I'm just a bit frustrated and trying to see the virtue of the change, that's all.  Is it that using switchMap allows the application to replace the input stream while keeping the websocket open?
Anyway, thanks for providing this library.

**Comment by ohjames** [comment]
Hi,

Each websocket has its own signgle input since this change. While this involves a functional complication, it involves a contextual simplification. I'm happy to provide whatever support you need,
within reason.

Warmly,
James

On 31 October 2019 23:24:10 GMT+08:00, jcairney <notifications@github.com> wrote:
>Hi James,
>
>This is not a bug, this is just the only avenue I could find to give
>feedback.  Back in 2017 my team started using your
>angular2-websocket-service library at the point where it was still a
>service.  I started this week to upgrade from versions of Angular from
>4 to 8, and needed to move up to using rxjs-websockets because the
>version of RxJS included in angular2-websocket-service was not
>compatible with the version of RxJS I had rolled up to in my project. 
>Looking at your latest readme.md, I'm barely been able to understand
>the new API you've implemented in version 7.0 without a lot of head
>scratching.  I've looked through the source code of the library and I
>find the internals equally difficult to reason about now, compared to
>what it was two years ago.  I've looked through the commits to try and
>understand when the changes occurred and why they were made.
>
>Specifically the change away from taking an input observable in the
>connect method, in the January 7th commit -
>eaf8fc411f4bbb6f6ca10c57622ef10432e6117d - has a commit message to the
>effect of "simplify connection status handling", but I think it doesn't
>simplify the library as a whole.  It was easier to reason about the
>system when one was passing in a stream of input.  Now the input is
>somehow supplied through something we subscribe to the output.  I get
>that we are receiving a factory as output when we subscribe, but it's
>still convoluted in my opinion, and the naming doesn't help sort it
>out.  I'm sure I'll be able to figure it out.  I'm just a bit
>frustrated and trying to see the virtue of the change, that's all.  Is
>it that using switchMap allows the application to replace the input
>stream while keeping the websocket open?
>Anyway, thanks for providing this library.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ohjames/rxjs-websockets/issues/116

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ohjames** [comment]
The observable issues a function when the connection occurs. You pass this function an input observable for passing messages to the websocket. This function then returns an observable you can use to subscribe to messages sent from the server. Feel free to ask questions if that isn't clear.

**Comment by insidewhy** [comment]
Or it's like this...

* user: rxjs-websockets open me a connection when somebody subscribes to the observable.
* rxjs-websockets: A new websocket has been opened, please give me an observable to use to send messages to it (i.e. it responds with a function when the websocket is opened).
* user: here is the observable to take messages from (i.e. user should pass observable to the function).
* rxjs-websockets: And here is the observable representing the output messages.
