### ISSUE TITLE
Add authentication header

### ISSUE THREAD

**Issue by henkverschoor1994** [ohjames/rxjs-websockets#12]
Hello,

How can I add authentication header to my websocket?
The websocket URL is `ws://user:password@localhost:8080` but on the server is no authentication header.

This is my connection: 
```
      this.messages = websocketConnect(
        url,
        this.inputStream = new QueueingSubject<any>(),
        url => new WebSocket(url.toString()),
        false
      ).messages.share();
```

**Comment by ohjames** [comment]
https://stackoverflow.com/questions/28965210/configuring-authentication-headers-for-websocket-connection
