### ISSUE TITLE
Question: Can I use this library for STOMP over websocket?

### ISSUE THREAD

**Issue by 1ambda** [ohjames/rxjs-websockets#14]
Hi, I am building a server which uses STOMP over websocket. 

Since the API of rxjs-websockets is cleaner than other libraries, I would like to use this library for client side websocket connection

- Does this library supports STOMP over websocket? 
- Or is there an work around can I use? 

Thanks!

**Comment by ohjames** [comment]
Anything that can be done with websockets can be done rxjs-websockets.

**Comment by ohjames** [comment]
You probably just need to use the `map` operator on both the input subject and messages observable... FRP is a great way of doing anything IMO :)
