### ISSUE TITLE
Support WebSocket's protocol parameter

### ISSUE THREAD

**Issue by NarinLab** [ohjames/rxjs-websockets#15]
Hello,

Thankyou for the great works, I need help on documentation about how to define websocket protocol parameter like this one:

var exampleSocket = new WebSocket("ws://www.example.com/socketserver", "**protocolOne**");

Where should I declare that?

Please help, thank you.

**Comment by ohjames** [comment]
This will be in version 3, out later today.

**Comment by ohjames** [comment]
Almost finished the work on this, will be out very soon.

**Comment by ohjames** [comment]
Version `3.0.0` has just been published to npm with support for `protocols`.
