### ISSUE TITLE
 Property 'share' does not exist on type 'Observable<string>'.

### ISSUE THREAD

**Issue by rahulrsingh09** [ohjames/rxjs-websockets#17]
When i try to implement the dummy example i get this error  Property 'share' does not exist on type 'Observable<string>'.

**Comment by axleonard** [comment]
Are you using the latest version of RxJS? This is working for me with 5.4.3.

**Comment by ohjames** [comment]
You have not imported rxjs correctly. Please read their documentation.

**Comment by ohjames** [comment]
Also a duplicate of #16

**Comment by ohjames** [comment]
@axleonard Thanks, I've added this import to the example in the readme.
