### ISSUE TITLE
rxjs-websockets can't install

### ISSUE THREAD

**Issue by MicroLord** [ohjames/rxjs-websockets#19]
npm install -S rxjs-websockets
npm ERR! Unexpected end of input at 1:1171
npm ERR! 20d02c019dd","size":7257,"noattachment":false,"tarball":"http://regis
npm ERR!

thanks

**Comment by ohjames** [comment]
npm issue

**Comment by ohjames** [comment]
npm cache clear
rm -rf node_modules
Check your internet.
Try again.

**Comment by MicroLord** [comment]
sorry , i tried many times , it do not work , you hava a try locally ?

**Comment by MicroLord** [comment]
node v8.6.0
npm  v5.3.0

**Comment by MicroLord** [comment]
thanks ,i konw the reason ,i use the taobao registry
