### ISSUE TITLE
OnClose event trigger

### ISSUE THREAD

**Issue by endertls** [ohjames/rxjs-websockets#22]
Hello,
I'm trying to implement auto reconnect with your angular 4 example but I can't find a way to plug the on close event to this block:

 this.messages = websocketConnect(
      'ws://127.0.0.1:4201/ws',
      this.inputStream = new QueueingSubject<string>()
    ).messages.share()

Have you an example of implementation for autoreconnect or close detection?

Thank you for your time

**Comment by ohjames** [comment]
Read the README before opening an issue? And don't use issues for support?

**Comment by ohjames** [comment]
Please read the README before opening issues as the information is there.
