### ISSUE TITLE
online/offline state

### ISSUE THREAD

**Issue by xtreemrage** [ohjames/rxjs-websockets#24]
Do you have an example on how to get the online/offline state of your websocket server, through this api?
I want to know, if the websocket server is offline and notify the end-user.

**Comment by ohjames** [comment]
How would you be able to distinguish between a network interruption, a routing issue and the server being legitimately offline?

**Comment by ohjames** [comment]
The best you can do is notify the user if connection fails or takes longer than n seconds, this is pretty trivial with rxjs but a question for stackoverflow etc. this forum is for bug reports.

**Comment by xtreemrage** [comment]
@ohjames 
I have the question on overflow, I was hoping you had also in insight about this.
Thanks for the information, next time I will keep it to bugs.
