### ISSUE TITLE
Not able to get binary messages

### ISSUE THREAD

**Issue by Murtuzakabul** [ohjames/rxjs-websockets#28]
Binary messages does have the length but actual blob does not have the message binary blob. It seems like the message is always observable with type of message is string only (index.ts, line 8) = "messages: Observable&lt;string&gt;"

**Comment by ohjames** [comment]
Thanks for the issue, haven't considered binary support yet. No time to implement myself for the next 5 weeks, but can review/merge a PR if you want to fix it in the meantime. Otherwise I'll look into this when I'm back from holiday.

**Comment by ohjames** [comment]
Fix in progress on the v7 branch.

**Comment by ohjames** [comment]
Version 7.0.0-alpha.1 has this support now. Sorry for the wait. Please be aware there will be one more backwards incompatible change before `7.0.0` is released so please pin the version appropriately.
