### ISSUE TITLE
Missing "var WebSocket = require("ws")" in "node_modules/rxjs-websockets/lib/index.js

### ISSUE THREAD

**Issue by ToanP** [ohjames/rxjs-websockets#29]
Hi James,

I tried to integrate your lib into my node project which is raw javascript but not Typescript project. With some fixes for Typescript compilation, I faced an issue:

number of connected websockets: 0
/Volumes/DATA/sources/node_server/node_modules/rxjs/Observable.js:165
                throw sink.syncErrorValue;
                ^

ReferenceError: WebSocket is not defined
    at defaultWebsocketFactory (/Volumes/DATA/sources/node_server/node_modules/rxjs-websockets/lib/index.js:5:58)
    at Observable._subscribe (/Volumes/DATA/sources/node_server/node_modules/rxjs-websockets/lib/index.js:10:22)
  .....

I fixed this issue by add the line of code 
"var WebSocket = require("ws")" in "node_modules/rxjs-websockets/lib/index.js

Could you please review the fix and have a new version of you rxjs-websocket library?

Thanks,
Toan Pham
Developer

**Comment by ohjames** [comment]
This is covered by the README. Search for "factory". Your suggested fix does not consider that this library is also for use by browsers.

**Comment by EvanCarroll** [comment]
This isn't at all clear which is why there are 20 questions or so on StackOverflow and even duplicate bug issues here on this #26

**Comment by ohjames** [comment]
@EvanCarroll Then open a PR to improve the docs.
