### ISSUE TITLE
Get readyState

### ISSUE THREAD

**Issue by msholly** [ohjames/rxjs-websockets#3]
Thanks for your work on this project. I'd like to be able to check the status of the socket with the Websocket readyState attribute. Does this have a way to accomplish this? Or should it be handled outside of your library?

readyState docs 
https://developer.mozilla.org/en-US/docs/Web/API/WebSocket#Ready_state_constants

**Comment by ohjames** [comment]
The connectionStatus and message observables can be used to infer every state except "CLOSING".

**Comment by msholly** [comment]
Awesome I'll look into that. Thank you.

**Comment by ohjames** [comment]
@fxck it's actually a count of the number of connected websockets, not a `0` or `1` status. Every connection not in that count is closed.

**Comment by ohjames** [comment]
@fxck yep, you can do this with the `scan` operator or `distinctUntilChanged` :)
