### ISSUE TITLE
Planned release of RxJS 6 support?

### ISSUE THREAD

**Issue by dope9967** [ohjames/rxjs-websockets#36]
I see that https://github.com/ohjames/rxjs-websockets/pull/33 is already merged and RxJS 6 support is in master branch, so when the release is expected with this fix? :)

**Comment by ohjames** [comment]
Releasing later today

**Comment by bongiova61** [comment]
It seems that rxjs6 compatible version has not been released yet

**Comment by ohjames** [comment]
Version 5.0.0 released today, sorry for the delay.

**Comment by csoft2k** [comment]
We are getting an error message with the new 5.0.0 version:
`ERROR in src/app/websocket-client.service.ts(22,13): error TS2345: Argument of type 'QueueingSubject<string>' is not assignable to parameter of type 'Observable<string>'.
  Property 'share' is missing in type 'QueueingSubject<string>'.`

The implementation was working with Angular5. Should it be adapted in some way?
Thanks!

**Comment by ohjames** [comment]
Looks like typings for rxjs 5

**Comment by csoft2k** [comment]
Thanks for your hint @ohjames.
Our imports look like:
    "rxjs": "^6.2.0",
    "rxjs-compat": "^6.2.0",
    "rxjs-websockets": "^5.0.0",
So I think we got all references up to date. Any ideas will be welcome.

**Comment by ohjames** [comment]
Are you using QueueingSubject 0.3?

**Comment by csoft2k** [comment]
No - that was the issue.
Thanks again, @ohjames :)
