### ISSUE TITLE
Issue With retryWhen

### ISSUE THREAD

**Issue by DeepakArora76** [ohjames/rxjs-websockets#39]
Below changes that you made will make **retryWhen**  not working as "if (forcedClose) observer.complete();" makes observer completes.

return () => {
      forcedClose = true;
      if (inputSubscription) inputSubscription.unsubscribe();

      if (socket) {
        closed();
        socket.close();
      }
    };

**Comment by ohjames** [comment]
I don't understand, maybe the markdown formatting is obscuring the info. Could you restate the problem or try editing your formatting.

**Comment by ohjames** [comment]
retryWhen should only affect errors? That force close flag is only set when the user explicitly closes the connection meaning there is no error.

**Comment by DeepakArora76** [comment]
Hi,

The document on [retry / retryWhen](http://reactivex.io/documentation/operators/retry.html) says "**if a source Observable emits an error, _resubscribe_ to it in the hopes that it will complete without error**"

During **resubscribe** process, return statement (metioned below) will be executed. Please refer to your latest changes.
```
    return () => {
      forcedClose = true
      if (inputSubscription)
        inputSubscription.unsubscribe()

      if (socket) {
        closed()
        socket.close()
      }
    }
  }
```

What does it means? It means that  **forcedClose** will be set to true, and a call to **socket.close()** (see above code) will results in call to callback **socket.onclose**

```
    socket.onclose = (event: CloseEvent) => {
      closed()
      if (forcedClose)
        observer.complete()
      else
        observer.error(new Error(event.reason))
    }
```

And behaviour leads to **retryWhen** stops attempting to resubscribe as the observer gets complete notification.

This is what I experienced with the version of Websocket I am using. The one I am using is not browser based websocket, but something different (nativescript based).

**Comment by DeepakArora76** [comment]
I leave it up to you to reopen this issue as the issue what I see is with not a browser.

**Comment by ohjames** [comment]
@DeepakArora76 Thanks for the explanation, this work was done by @cPu1 in this PR: https://github.com/ohjames/rxjs-websockets/pull/34

Will revert it.

**Comment by ohjames** [comment]
@DeepakArora76 Reverted that commit, thanks very much for your report!

**Comment by ohjames** [comment]
@DeepakArora76 Wait, isn't this also an issue even without the `forceClose` stuff?

**Comment by ohjames** [comment]
@DeepakArora76 Yes after you get an error, `socket` gets set to `null`. Therefore `socket.close()` won't be called when you retry the connection.

**Comment by DeepakArora76** [comment]
@ohjames:  This is also an issue without the forceClose stuff.  Where is the code do you set the socket to null?

**Comment by DeepakArora76** [comment]
Thanks :)

**Comment by ohjames** [comment]
Sorry meant to say `6.0.1`. Thanks again!

**Comment by rfestag** [comment]
If I'm understanding correctly, I seem to still be having this issue with 6.0.1. I basically create an object that should immediately connect in the constructor, and whenever a "query" happens, it should share a websocket that will retry the connection every `retryInterval` ms. Two cases don't work as expected:
1) If my websocket server is not running when this page comes up, it never retries the connection
2) If I restart my websocket server while this is running, it never retries the connection.

Am I doing something wrong in here? Or is this still a bug?

```javascript
const defaultFactory = (url, protocols) => new WebSocket(url, protocols)
export class WebsocketSource extends Source {
  constructor(name, {url, factory=defaultFactory, retryInterval=1000}) {
    super(name)
    this._input = (new QueueingSubject()).map(message => JSON.stringify(message))

    const { messages, connectionStatus } = websocketConnect(url, this._input, undefined, factory)

    this.messages = messages
      .retryWhen(errors => errors.delay(retryInterval))
      .map(message => JSON.parse(message))
      .share()
    this.connectionStatus = connectionStatus
  }
  send(data) {
    this._input.next(data)
  }

  /**
   * @return {Observable} An Observable indicating whether this source is "available"
   */
  health() {
    return this.connectionStatus
  }
  query() {
    return this.messages.map(updates => {
      //code here to map results
    })
  }
}
```

**Comment by ohjames** [comment]
For anyone watching via this issue, @rfestag's scenario isn't as straightfoward as this one and you may not experience it yourselves, but I recommend updating to `6.0.2` which ensures that `complete()` is never called on an observer after `error()`.
