### ISSUE TITLE
Document and samples are not up to date with the new revision of "rxjs": "^6.1.0"

### ISSUE THREAD

**Issue by DeepakArora76** [ohjames/rxjs-websockets#41]
Samples need updation. 

https://github.com/ReactiveX/rxjs/blob/master/docs_app/content/guide/v6/migration.md.

**Comment by ohjames** [comment]
@DeepakArora76 Thanks for opening this ticket. I've been meaning to update them so good to have this ticket to track it. I also want to add a `CHANGELOG`.

**Comment by ohjames** [comment]
Fixed now!
