### ISSUE TITLE
DOMException: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.

### ISSUE THREAD

**Issue by AlexanderKozhevin** [ohjames/rxjs-websockets#42]
I've application which is loaded via HTTP and tries to connect to HTTP. 
It's not right, but even though it shouldn't crash my application totally. But it does.

**Comment by AlexanderKozhevin** [comment]
@ohjames Is there any way to prevent application crash?

**Comment by ohjames** [comment]
Ctrl-l ctrl-c

Then paste the URL somewhere. Notice how it is https. Then regret not believing the error message ;)

**Comment by ohjames** [comment]
You can prevent the application crash by using not using an inappropriate ws URL.

**Comment by ohjames** [comment]
I could make it to the code detects the constructor failure and creates an observable which emits a single error, but that sounds like worse behaviour. This is why they issue the warning from the WebSocket constructor right... to tell you to use the right kind of URL. You should be using a `//` or `https://` prefixes URL for your ws and never http.
