### ISSUE TITLE
Closing socket connection

### ISSUE THREAD

**Issue by mustafaekim** [ohjames/rxjs-websockets#5]
I think the readme is misleading, because the code below only unsubscribes but does not close the socket connection. 
`messagesSubscription.unsubscribe()`

hence, how can I close the socket connection ?

(I use Angular)

**Comment by ohjames** [comment]
This should close the connection, but it would depend exactly on how you are using the Observable (e.g. whether you are using share, publish etc.)

Could you paste more of your code sample?

The code looks fine to me but I may have missed something, there may be a bug. I can test it out when I have some more time.

**Comment by mustafaekim** [comment]
Angular > Service
```ts
import { Injectable } from '@angular/core'
import { QueueingSubject } from 'queueing-subject'
import { Observable } from 'rxjs/Observable'
import websocketConnect, { Connection } from 'rxjs-websockets'
import { Config } from "../common/config";


@Injectable()
export class WebSocketService {

  private inputStream: QueueingSubject<any>
  public messages: Observable<any>

  public connect(path: string) {
    if (this.messages)
      return

    // Using share() causes a single websocket to be created when the first
    // observer subscribes. This socket is shared with subsequent observers
    // and closed when the observer count falls to zero.
    //this.messages = 
    
    this.messages = websocketConnect(
      Config.getEnv("wsRoot") + path,
      this.inputStream = new QueueingSubject<any>()
    ).messages.share()
  }

  public send(message: any): void {
    // If the websocket is not connected then the QueueingSubject will ensure
    // that messages are queued and delivered when the websocket reconnects.
    // A regular Subject can be used to discard messages sent when the websocket
    // is disconnected.
    this.inputStream.next(message)
  }

  public disconnect(){
    //???
  }


}
```

Angular > Component 

```ts
import { ActivatedRoute } from '@angular/router';
import { EventClientFetchAction } from "./../store/reducer/event-client.reducer";
import { AppState } from '../store/state/app-state';
import { Store } from '@ngrx/store';
import { Component, OnInit } from '@angular/core';
import { Observable } from "rxjs/Observable";
import { EventClient } from "../../shared/model/event-client";
import { WebSocketService } from "../../websocket/websocket.service";
import { Subscription } from "rxjs/Subscription";

@Component({
    templateUrl: 'connect-event.component.html'
})

export class ConnectEventComponent implements OnInit {

    private code: string;

    loading$: Observable<boolean>;
    eventClient$: Observable<EventClient>;
    reTry: boolean;


    private socketSubscription: Subscription
    private ponger: Subscription;

    constructor(
        private route: ActivatedRoute
        , private store: Store<AppState>
        , private webSocketService: WebSocketService
    ) {
        this.loading$ = store.select(state => state.eventClient.loading);
        this.eventClient$ = this.store.select(state => state.eventClient.item)

        this.store.select(state => state.eventClient).subscribe(eventClientContainer => {
            this.reTry = (eventClientContainer.httpResponseCode != 200 || !eventClientContainer.serverResponse.isOk()) ? true : false;
        })
    }

    ngOnInit() {
        this.route.params.subscribe(params => {
            this.code = params['code'];
            this.fetchEventClient();
        });
    }

    fetchEventClient() {
        this.store.dispatch(new EventClientFetchAction(this.code));
    }

    connect() {
        this.webSocketService.connect("ws/v1")
        this.socketSubscription = this.webSocketService.messages.subscribe((message: any) => {
            console.log('received message from server: ', message);
            console.log(message.action === 'ping');
            console.log(message.action);
        })

        this.ponger = this.webSocketService.messages.filter(msg => msg.action === 'ping').subscribe(
            (msg) => {
                console.log("I AM HERE TO PONG!");
                this.webSocketService.send({action: "pong"})
            }
        );
    }

    send() {
        // send message to server, if the socket is not connected it will be sent
        // as soon as the connection becomes available thanks to QueueingSubject
        this.webSocketService.send({ type: 'helloServer' })
    }

    disconnect() {
        this.socketSubscription.unsubscribe();
        
    }

}
```

**Comment by ohjames** [comment]
When the number of subscribers to a `share()`d observable drops to 0 it should run the disposal routine which in the rxjs-websockets code closes the web socket connection. If not it's a bug, I'll have to verify myself.

**Comment by mustafaekim** [comment]
OK, I could not observe that. Maybe that I should wait for a while?

What is the right pattern of closing the socket connection when the user clicks on a button on the webpage?

a) controller closes the socket connection through the websocket service's method
b) controller only unsubscribe and if no subscriber left, the connection is closed automatically
c) controller sends a new action to the server and the server closes the connection

(I think the library should support all options)

**Comment by ohjames** [comment]
It does support all of these options, you would handle it via rxjs operators like `publish()`, `share()` etc.

It's important to have a good understanding of cold observables to understand how to use this library effectively, when you get that you'll see how to do (a-c).

**Comment by ohjames** [comment]
I'd advise checking this out: https://blog.thoughtram.io/angular/2016/06/16/cold-vs-hot-observables.html

It's liked in the README. TBH you'll need that understanding to do anything slightly advanced with rxjs.

**Comment by mustafaekim** [comment]
Hi, thanks for the resource, I've checked it, it was very useful. 

I've found the mistake, thanks for your support. Actually I have two different subscriptions but I close only one of them. I fixed it like that:

```ts
    disconnect() {
        if (this.socketSubscription){
            this.socketSubscription.unsubscribe();
        }
        if(this.ponger){
            this.ponger.unsubscribe();
        }            
    }
```

**Comment by ohjames** [comment]
Cool, I'm writing some unit tests, hopefully those will lead to more understanding.

**Comment by ohjames** [comment]
At least your mistake demonstrated how the `share()` operator works to you, it's pretty cool no? Rxjs is great!

**Comment by mustafaekim** [comment]
I have to look into Rxjs more deeply :)

**Comment by mustafaekim** [comment]
It looks like if I subscribe to the connectionStatus, even if I unsubscribe, the socket is not closed :)

do you think that can be true?

**Comment by mustafaekim** [comment]
Oh, I put the share() and it worked. It seems like I didnt get the idea :))

```ts
    let con: Connection = websocketConnect(
      Config.getEnv("wsRoot") + path,
      this.inputStream = new QueueingSubject<any>()
    );
    
    this.messages = con.messages.share();
    this.status = con.connectionStatus.share();
```

**Comment by ohjames** [comment]
There's no point sharing the connection status, it's a hot observable. Doing so is a minor performance hit for nothing.

**Comment by mustafaekim** [comment]
OK, however without share, it does not close the socket connection even after unsubscription

**Comment by ohjames** [comment]
That should be impossible, I suspect you've made a mistake elsewhere.

**Comment by ohjames** [comment]
See here in the code:

https://github.com/ohjames/rxjs-websockets/blob/master/src/index.ts#L28

connection status is a BehaviorSubject, a hot observable.

**Comment by mustafaekim** [comment]
yes u r right (again) thanks!
