### ISSUE TITLE
Catching Websocket Connection Errors in ConnectionStatus Observable

### ISSUE THREAD

**Issue by TaylorChristie** [ohjames/rxjs-websockets#50]
Currently it seems that both the messages and connectionStatus observables do not handle errors with an invalid websocket connection. I am attempting to retry connection if one of two things happens

1. I cannot establish a connection to the websocket at all
2. The websocket is not replying to my messages

Now, I can rudimentarily handle both of these cases by doing this:

```ts
messages
            .race(Observable.never().timeout(this.initialMessageTimeout * 1000))
            .pipe(retryWhen(errors => errors.pipe(
                tap(val => {
                    this.connectionIssues = true;
                    this.toast.error('We are having issues communicating with our chat service.');
                }),
                delay(1000))))
            .subscribe((msg: string) => {});
```

essentially, after n seconds of not recieving a message from the websocket I will show an error to the end user and attempt to retry the connection.

However, when testing with the websocket server down I see errors in my console for the websocket connection, but neither messages or connectionStatus have any errors thrown in it, which I think should probably be the case since it is handling the websocket connection. I see in the code that you handle this here: 

```
    socket.onerror = (error: ErrorEvent) => {
      closed()
      observer.error(error)
    }
```

however I cannot collect any error via:

```ts
messages
            .race(Observable.never().timeout(this.initialMessageTimeout * 1000))
            .pipe(retryWhen(errors => errors.pipe(
                tap(val => {
                    this.connectionIssues = true;
                    this.toast.error('We are having issues communicating with our chat service.');
                }),
                delay(1000))))
            .subscribe((msg: string) => {}, (err) => {console.log(err)});
```

Which i think should be the case.

I'm proposing that the connectionStatus observable should also attempt to carry information regarding the state of the connection to the websocket so implementations can leverage the knowledge of the websocket connection.

**Comment by ohjames** [comment]
> the connectionStatus observable should also attempt to carry information regarding the state of the connection to the websocket

It does let you know whether the websocket is connected or not, what else would you like to see?

I'm gonna improve the connection status handling soon in a new release, but I'm not exactly sure what you wanna see.

You could merge an interval observable with the connection status observable to log messages while awaiting connection?

BTW I don't like the way your code uses `tap` non-reactively to set state. It's great to use tap for side effects such as your console log but setting state like that is not great.

**Comment by ohjames** [comment]
See https://developer.mozilla.org/en-US/docs/Web/API/WebSocket

There is no event about connection status, this library is handling all the events there. It sounds like you need some kinda ping/pong system or to combine a timer with your wait for connection, but that should be done in a layer on top of this library.

Please reopen this or create a new issue if you have any concrete suggestions that are possible with the WebSocket API.

BTW soon version 7 of this API will make connection status handling more easy, you'll have a single connection status stream which will emit observables as a new connection is made.

**Comment by gharia** [comment]
Hey @insidewhy, thanks for your efforts.
I have a query (or maybe I am missing something). How to know the status of the connection? and what is the preferred way to propagate the connection status change to the parent component? I am using version 8.0.1 with the following way:
`
this.messages$ = socket$.pipe(
      switchMap((getResponses: GetWebSocketResponses<string>) => {
        this.connectionStatus$.next(1);
        return getResponses(this.inputStream$);
      }),
      retryWhen(errors => {
        console.log("disconnected");
        this.connectionStatus$.next(0);
        return errors.pipe(
                filter(err => !equals(err.message, normalClosureMessage)),
                delay(1000));
      }),
      share(),
  );
  
  
  this.messagesSubscription = this.messages$!.subscribe(
      _ => {
        return;
      },
      (error: Error) => {
        const { message } = error;
          this.connectionStatus$.next(0);
          console.log('socket was disconnected due to error:', message);        
      },
      () => {
        // The clean termination only happens in response to the last
        // subscription to the observable being unsubscribed, any
        // other closure is considered an error.
        this.connectionStatus$.next(0);
        console.log('the connection was closed in response to the user')
      },
    )
`
It starts reconnection attempts when I close connection from the server. However, I do not see these console logs and it does not change the `connectionStatus$`. Also when I manually disconnection network adapter, it does not reconnect and does not change `connectionStatus$`. So what is the proper way to handle all disconnection events (including internet connectivity lost)?
