### ISSUE TITLE
Please Include License File

### ISSUE THREAD

**Issue by clchandan** [ohjames/rxjs-websockets#51]
Hi Looks like you have License as ISC but since you don't have a license file the copyright and license attribution would not apply.

**Comment by ohjames** [comment]
Sorry for not seeing this, I stupidly turned off git notification emails ;) I'll add the license file tonight.

**Comment by ohjames** [comment]
https://github.com/ohjames/rxjs-websockets/blob/master/LICENSE.txt :) Thanks again for your report and sorry it took so long for me to get around to this.
