### ISSUE TITLE
How to make use of this in angular 4 project?

### ISSUE THREAD

**Issue by zymr-keshav** [ohjames/rxjs-websockets#53]
I have project where need to use WebSocket and your library seems me a good fit as it uses observables and rxjs but when I installed it gives this warning in terminal.

```
npm WARN queueing-subject@0.3.0 requires a peer of rxjs@^6.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN rxjs-websockets@6.0.2 requires a peer of rxjs@^6.1.0 but none is installed. You must install peer dependencies yourself.
```

I am having **rxjs:^5.1.0** in package.json and when I tried to upgrade only rxjs version it throws various errors.

> ng-v 
```
Angular CLI: 1.7.4
Node: 8.9.2
OS: darwin x64
Angular: 4.4.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, tsc-wrapped

@angular/cli: 1.7.4
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.3.4
webpack: 3.11.0
```

So I just want to know Can I use this into my project or if not then what changes required to use this ?

**Comment by ohjames** [comment]
Look up peer dependencies. You just need to npm/yarn install rxjs.

**Comment by ohjames** [comment]
If you are stuck on rxjs 5 you need to use an older version of the package.

**Comment by ohjames** [comment]
Angular has moved onto rxjs 6 now and so have the most recent versions of this library.
