### ISSUE TITLE
Omitting protocol parameter to websocketConnect() results in bad header on Firefox

### ISSUE THREAD

**Issue by JanSoderback** [ohjames/rxjs-websockets#55]
Omitting the protocols parameter to websocketConnect() causes Firefox to send an invalid protocol header to the server

Calling `websocketConnect(url, this.input)` results in this header in the HTTP Upgrade request:

    Sec-WebSocket-Protocol: undefined

The WebSocket connection immediately closes and Firefox prints a "Firefox can’t establish a connection to the server at [URL]" message in the console.

But if I add an empty array parameter: `websocketConnect(url, this.input, [])`, there is no `Sec-WebSocket-Protocol` header in the HTTP Upgrade request.

Chrome 70 doesn't create the `Sec-WebSocket-Protocol` header in either case.

I am proxying the WebSocket connection through nginx to a Windows server running a custom service that uses the WebSocket implementation in .NET.

Versions:
 - rxjs-websockets 6.0.2
 - Firefox 63 on Ubuntu 16.04
 - nginx 1.14.0-0ubuntu1.2
 - .NET Framework 4.7

**Comment by ohjames** [comment]
@JanSoderback Thanks for your report, @illusionalsagacity actually fixed this recently but it wasn't in a release. I've just published 6.0.3 with the fix, please let me know if it works for you and thanks once again to that person for the fix :)
