### ISSUE TITLE
Cannot close websocket before open

### ISSUE THREAD

**Issue by iFwu** [ohjames/rxjs-websockets#59]
I try unsubscribe the unconnected websocket open observable, but not work.

**Comment by ohjames** [comment]
You cannot close a door that is already closed. Same goes for WebSocket connections.

**Comment by ohjames** [comment]
Please reopen this if you have time to contribute more information, there's not enough to go on in this ticket.

**Comment by iFwu** [comment]
> You cannot close a door that is already closed. Same goes for WebSocket connections.

I know. However, when unsubscribe a rxjs-websocket, I lost control over it, and can't close it after it opens.

I modify some code and it now can be close before opening: see PR #60

**Comment by ohjames** [comment]
Thanks, the PR makes it clear. If you could make that one small change I'll merge it.

**Comment by ohjames** [comment]
PR wasn't linked to this issue but it has been fixed.

**Comment by akarelas** [comment]
Hi. Do you intend to publish this fix anytime soon? I'm trying to create a library that depends on yours, that's why I'm asking.

Thanks.
