### ISSUE TITLE
Override socket.onmessage

### ISSUE THREAD

**Issue by cristianp6** [ohjames/rxjs-websockets#6]
Hi James, first of all thanks for this library!
I need to override `socket.onmessage` behaviour in order to prevent [JSON.parse](https://github.com/ohjames/rxjs-websockets/blob/master/src/index.ts#L52) and handle some binary data instead of string messages: could you please give an example on how to do this? Perhaps passing a custom `WebSocketFactory` as third param of `websocketConnect`?
Tnx!

**Comment by ohjames** [comment]
Thanks for your message! Yes the `JSON.parse` thing has been bothering me for a while, I'm not sure if it was the right thing to make it the default and not just leave it up to the user.

I could create a new semantically versioned release that disables this functionality, or I could make it an option and create a point release with the change. Which do you think is best? I'm tending towards the latter... probably.

**Comment by ohjames** [comment]
The more anal part of me is tending towards the former :)

**Comment by cristianp6** [comment]
Personally I would take away JSON parsing and leave it up to users.
Anyway, it should be fine to give an option to enable or disable JSON parsing in the socket.onmessage and socket.send.

But how about a custom WebSocketFactory as third param?

**Comment by ohjames** [comment]
Cool so it's 1.3 vs 0.7 (the more anal 0.3 part of me agrees with you). So I'll make a new release with the json parsing handled by the user. Can be trivially handled by `map` anyway. Yeah I think this is the right way to go.

**Comment by ohjames** [comment]
I'll have it for you in the next few days, if you need it sooner feel free to open a PR.

**Comment by ohjames** [comment]
Oh I forgot to let you know, the second argument is already a WebSocket factory.
