### ISSUE TITLE
Response & Timeout or any other pattern

### ISSUE THREAD

**Issue by mustafaekim** [ohjames/rxjs-websockets#7]
It may or may not be related to the scope of the library however I could not find enough information on internet so that I ask.

When I use the send method of the websocket service, is there anyway that I can follow up the response? I know that I can send messages in one tunnel and listen to the responses in another tunnel but what I didnt understand is how I will get them all in a meaningful order. Here is an example case:

When I click on a button on my webpage (join room) I send a JOIN_ROOM_REQUEST to the websocket on the server. And meanwhile I disable the button because I do not want the user to click again and be prompted when his join request is accepted and executed. If everything goes well, the server will send an event over the websocket so that I can now let the user to join the room. However what if the server does not respond at all? How will I handle this situation? The button hanged disabled and the state cannot be updated back to its initial state.

**Comment by ohjames** [comment]
I'm happy to help with support but could you post support questions on stackoverflow and DM me over Twitter so that I can get around to responding. Thanks!

**Comment by ohjames** [comment]
... DM me *the link*

I meant to say.

**Comment by mustafaekim** [comment]
I've even found your CV but could not find you on twitter :)

 https://stackoverflow.com/q/44884363/5043925?stw=2

**Comment by ohjames** [comment]
Twitter icon on the bottom of my website has it :)
